spring:
  application:
    name: litewechat
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
server:
  port: 8080
logging:
  level:
    com.tery.edu.litewechat: debug
  file: /opt/tery/litewechat/log/litewechat.log